### ISSUE TITLE
Increase maximum string length

### ISSUE THREAD

**Issue by t4deon** [datasharingframework/dsf#138]
We use the DSF with great success. However, we run into issues when posting large Binary resources onto the FHIR server.

```
fhirserver-1  | WARN jetty-server-2986 - DataFormatExceptionHandler.toResponse(40) | Error while parsing resource: Failed to parse JSON encoded FHIR content: String length (20045301) exceeds the maximum length (20000000), returning OperationOutcome with status 403 Forbidden
```
Is there any way to increase the maximum string length on the server side or any viable workaround that still uses the DSF?

Our particular setup is:
1. Sender: Post a Bundle with a Task and Binary resource onto the FHIR server. The Binary resource is referenced as a Task input. 
2. Receiver: Download the referenced Binary from the sender's server.

The used Binary has `contentType = application/json` if that matters.

Thanks.

Used DSF version for all components: 1.3.1

**Comment by hhund** [comment]
Hi @t4deon,

the max length parsing error is generated by the HAPI JSON parser and is likely the same issue as described in hapifhir/hapi-fhir#5205. The issue was fixed with HAPI 6.8.2. Due to problems with the validation of Task resources in HAPI versions after 5.1.0, we haven't been able to upgrade, but also haven't tried recently.

Until we upgrade our HAPI dependency, possible workarounds could be:
* Sending the transaction Bundle as XML `Content-Type: application/fhir+xml`.
* Creating the Binary and Task resources independently and Uploading the binary data directly without the JSON or XML Binary resource wrapper using for example `Content-Type: application/dicom`. See notes on uploading/downloading binary resources directly and the usage of the `X-Security-Context` header at https://www.hl7.org/fhir/R4/binary.html#rest

We do store the FHIR resources as JSON in our PostgreSQL database. But since the actual content of the binary resource is stored separately in a `BYTEA` column, I currently don't think that the max length error should reappear between the app and database.
